package edu.sliit.smartcampus.model;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_PENDING,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_UPDATED,
    TICKET_RESOLVED,
    TICKET_COMMENT_ADDED,
    USER_ROLE_CHANGED,
    ACCOUNT_SECURITY_ALERT,
    GENERAL
}
